<?php
/**
 * SodacardsDevpublicV1Product
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Sodacards
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SODACARDS Developer API
 *
 * Sell gift cards and game top-ups from your own systems.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Sodacards\Model;

use \ArrayAccess;
use \Sodacards\ObjectSerializer;

/**
 * SodacardsDevpublicV1Product Class Doc Comment
 *
 * @category Class
 * @description Product is one sellable item in the reseller catalog. Its id is what an order  line references. It never carries the supplier cost or routing.
 * @package  Sodacards
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SodacardsDevpublicV1Product implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'sodacards.devpublic.v1.Product';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'id' => 'string',
        'name' => 'string',
        'face_value' => '\Sodacards\Model\SodacardsDevpublicV1ProductFaceValue',
        'price' => '\Sodacards\Model\SodacardsDevpublicV1Money',
        'strike_price' => '\Sodacards\Model\SodacardsDevpublicV1Money',
        'bonus' => 'string',
        'min_quantity' => 'int',
        'max_quantity' => 'int',
        'purchasable' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'id' => null,
        'name' => null,
        'face_value' => null,
        'price' => null,
        'strike_price' => null,
        'bonus' => null,
        'min_quantity' => 'int32',
        'max_quantity' => 'int32',
        'purchasable' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'id' => false,
        'name' => false,
        'face_value' => false,
        'price' => false,
        'strike_price' => false,
        'bonus' => false,
        'min_quantity' => false,
        'max_quantity' => false,
        'purchasable' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'face_value' => 'faceValue',
        'price' => 'price',
        'strike_price' => 'strikePrice',
        'bonus' => 'bonus',
        'min_quantity' => 'minQuantity',
        'max_quantity' => 'maxQuantity',
        'purchasable' => 'purchasable'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'face_value' => 'setFaceValue',
        'price' => 'setPrice',
        'strike_price' => 'setStrikePrice',
        'bonus' => 'setBonus',
        'min_quantity' => 'setMinQuantity',
        'max_quantity' => 'setMaxQuantity',
        'purchasable' => 'setPurchasable'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'face_value' => 'getFaceValue',
        'price' => 'getPrice',
        'strike_price' => 'getStrikePrice',
        'bonus' => 'getBonus',
        'min_quantity' => 'getMinQuantity',
        'max_quantity' => 'getMaxQuantity',
        'purchasable' => 'getPurchasable'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('face_value', $data ?? [], null);
        $this->setIfExists('price', $data ?? [], null);
        $this->setIfExists('strike_price', $data ?? [], null);
        $this->setIfExists('bonus', $data ?? [], null);
        $this->setIfExists('min_quantity', $data ?? [], null);
        $this->setIfExists('max_quantity', $data ?? [], null);
        $this->setIfExists('purchasable', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id identifies the product; use it to place an order for this item.
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name is the human-readable product name.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets face_value
     *
     * @return \Sodacards\Model\SodacardsDevpublicV1ProductFaceValue|null
     */
    public function getFaceValue()
    {
        return $this->container['face_value'];
    }

    /**
     * Sets face_value
     *
     * @param \Sodacards\Model\SodacardsDevpublicV1ProductFaceValue|null $face_value face_value is the nominal value printed on the item (e.g. a 10 USD card),  which may differ from the currency the reseller pays in.
     *
     * @return self
     */
    public function setFaceValue($face_value)
    {
        if (is_null($face_value)) {
            throw new \InvalidArgumentException('non-nullable face_value cannot be null');
        }
        $this->container['face_value'] = $face_value;

        return $this;
    }

    /**
     * Gets price
     *
     * @return \Sodacards\Model\SodacardsDevpublicV1Money|null
     */
    public function getPrice()
    {
        return $this->container['price'];
    }

    /**
     * Sets price
     *
     * @param \Sodacards\Model\SodacardsDevpublicV1Money|null $price price is what the reseller pays, in FCFA. It is absent when the item is not  yet priced (listed but not purchasable).
     *
     * @return self
     */
    public function setPrice($price)
    {
        if (is_null($price)) {
            throw new \InvalidArgumentException('non-nullable price cannot be null');
        }
        $this->container['price'] = $price;

        return $this;
    }

    /**
     * Gets strike_price
     *
     * @return \Sodacards\Model\SodacardsDevpublicV1Money|null
     */
    public function getStrikePrice()
    {
        return $this->container['strike_price'];
    }

    /**
     * Sets strike_price
     *
     * @param \Sodacards\Model\SodacardsDevpublicV1Money|null $strike_price strike_price is an optional reference (pre-discount) price, in FCFA, for  display. Absent when there is none.
     *
     * @return self
     */
    public function setStrikePrice($strike_price)
    {
        if (is_null($strike_price)) {
            throw new \InvalidArgumentException('non-nullable strike_price cannot be null');
        }
        $this->container['strike_price'] = $strike_price;

        return $this;
    }

    /**
     * Gets bonus
     *
     * @return string|null
     */
    public function getBonus()
    {
        return $this->container['bonus'];
    }

    /**
     * Sets bonus
     *
     * @param string|null $bonus bonus describes any extra value granted with the item, e.g. \"+10%\". Empty  when there is none.
     *
     * @return self
     */
    public function setBonus($bonus)
    {
        if (is_null($bonus)) {
            throw new \InvalidArgumentException('non-nullable bonus cannot be null');
        }
        $this->container['bonus'] = $bonus;

        return $this;
    }

    /**
     * Gets min_quantity
     *
     * @return int|null
     */
    public function getMinQuantity()
    {
        return $this->container['min_quantity'];
    }

    /**
     * Sets min_quantity
     *
     * @param int|null $min_quantity min_quantity and max_quantity bound how many units an order line may buy.
     *
     * @return self
     */
    public function setMinQuantity($min_quantity)
    {
        if (is_null($min_quantity)) {
            throw new \InvalidArgumentException('non-nullable min_quantity cannot be null');
        }
        $this->container['min_quantity'] = $min_quantity;

        return $this;
    }

    /**
     * Gets max_quantity
     *
     * @return int|null
     */
    public function getMaxQuantity()
    {
        return $this->container['max_quantity'];
    }

    /**
     * Sets max_quantity
     *
     * @param int|null $max_quantity max_quantity
     *
     * @return self
     */
    public function setMaxQuantity($max_quantity)
    {
        if (is_null($max_quantity)) {
            throw new \InvalidArgumentException('non-nullable max_quantity cannot be null');
        }
        $this->container['max_quantity'] = $max_quantity;

        return $this;
    }

    /**
     * Gets purchasable
     *
     * @return bool|null
     */
    public function getPurchasable()
    {
        return $this->container['purchasable'];
    }

    /**
     * Sets purchasable
     *
     * @param bool|null $purchasable purchasable is true when the item has a price and can be ordered now.
     *
     * @return self
     */
    public function setPurchasable($purchasable)
    {
        if (is_null($purchasable)) {
            throw new \InvalidArgumentException('non-nullable purchasable cannot be null');
        }
        $this->container['purchasable'] = $purchasable;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


