<?php
/**
 * SodacardsDevpublicV1MoneyTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Sodacards
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SODACARDS Developer API
 *
 * Sell gift cards and game top-ups from your own systems.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Sodacards\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * SodacardsDevpublicV1MoneyTest Class Doc Comment
 *
 * @category    Class
 * @description Money is an amount in a currency&#39;s minor units, together with the currency&#39;s  ISO-4217 code and its number of decimal places, so the amount can be  interpreted without assuming the currency. XOF (the West-African CFA franc) has  no minor unit, so an XOF amount is a whole franc value.
 * @package     Sodacards
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SodacardsDevpublicV1MoneyTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SodacardsDevpublicV1Money"
     */
    public function testSodacardsDevpublicV1Money()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "minor_unit_exponent"
     */
    public function testPropertyMinorUnitExponent()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
