<?php
/**
 * SodacardsDevpublicV1OrderLineTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Sodacards
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SODACARDS Developer API
 *
 * Sell gift cards and game top-ups from your own systems.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Sodacards\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * SodacardsDevpublicV1OrderLineTest Class Doc Comment
 *
 * @category    Class
 * @description OrderLine is one product to buy on an order. input_fields carries the  purchase-form values a product requires (for example a game player id), keyed  by the field name from the product definition.
 * @package     Sodacards
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SodacardsDevpublicV1OrderLineTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SodacardsDevpublicV1OrderLine"
     */
    public function testSodacardsDevpublicV1OrderLine()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "product_id"
     */
    public function testPropertyProductId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "input_fields"
     */
    public function testPropertyInputFields()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
