<?php
/**
 * SodacardsDevpublicV1InputFieldSpecTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Sodacards
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SODACARDS Developer API
 *
 * Sell gift cards and game top-ups from your own systems.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Sodacards\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * SodacardsDevpublicV1InputFieldSpecTest Class Doc Comment
 *
 * @category    Class
 * @description InputFieldSpec describes one purchase-form field a product requires, so a  developer can build and validate an order line before placing it. Its value is  submitted on OrderLine.input_fields, keyed by this field&#39;s key.
 * @package     Sodacards
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SodacardsDevpublicV1InputFieldSpecTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SodacardsDevpublicV1InputFieldSpec"
     */
    public function testSodacardsDevpublicV1InputFieldSpec()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "key"
     */
    public function testPropertyKey()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "required"
     */
    public function testPropertyRequired()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "regex"
     */
    public function testPropertyRegex()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "options"
     */
    public function testPropertyOptions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
