<?php
/**
 * SodacardsDevpublicV1PlacedOrderTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Sodacards
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SODACARDS Developer API
 *
 * Sell gift cards and game top-ups from your own systems.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Sodacards\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * SodacardsDevpublicV1PlacedOrderTest Class Doc Comment
 *
 * @category    Class
 * @description PlacedOrder is the accepted order: its id, the amount charged to the wallet in  FCFA, and its current status.
 * @package     Sodacards
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SodacardsDevpublicV1PlacedOrderTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SodacardsDevpublicV1PlacedOrder"
     */
    public function testSodacardsDevpublicV1PlacedOrder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
