<?php
/**
 * DefaultApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Sodacards
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SODACARDS Developer API
 *
 * Sell gift cards and game top-ups from your own systems.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Sodacards\Test\Api;

use \Sodacards\Configuration;
use \Sodacards\ApiException;
use \Sodacards\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Sodacards
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DefaultApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteWebhook
     *
     * Delete a webhook endpoint.
     *
     */
    public function testDeleteWebhook()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getBalance
     *
     * Get wallet balance.
     *
     */
    public function testGetBalance()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOrder
     *
     * Get an order.
     *
     */
    public function testGetOrder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProduct
     *
     * Get a product.
     *
     */
    public function testGetProduct()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listCatalog
     *
     * List catalog products.
     *
     */
    public function testListCatalog()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listOrders
     *
     * List orders.
     *
     */
    public function testListOrders()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listWebhooks
     *
     * List webhook endpoints.
     *
     */
    public function testListWebhooks()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for ping
     *
     * Ping.
     *
     */
    public function testPing()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for placeOrder
     *
     * Place an order.
     *
     */
    public function testPlaceOrder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for registerWebhook
     *
     * Register a webhook endpoint.
     *
     */
    public function testRegisterWebhook()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for revealOrderCodes
     *
     * Reveal order codes.
     *
     */
    public function testRevealOrderCodes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for rotateWebhookSecret
     *
     * Rotate a webhook signing secret.
     *
     */
    public function testRotateWebhookSecret()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
